### ISSUE TITLE
Dependent packages are pinned too specifically

### ISSUE THREAD

**Issue by alapite** [pymc-learn/pymc-learn#23]
An unfortunate consequence of the manner in which the package dependencies are specified in the `requirements.txt` file is that it forces obsolete versions of important packages like numpy, pandas and scikit-learn on anyone who installs via `pip install pymc-learn`. I think it would be best to change the `requirements.txt` file to use `>=` instead of `==` wherever possible, unless it has been demonstrated that newer versions of specific dependencies genuinely exhibit incompatibilities. Otherwise, it might be better to warn prospective users that they ought to create a brand new virtual environment to use this package.

**Comment by Emaasit** [comment]
Thanks @alapite . I am working in a branch that has these changes. I will `git push` soon.

**Comment by Emaasit** [comment]
- [ ] Recommend using a virtual environment for this package.

- [ ] Properly specify pacakge dependencies

**Comment by Emaasit** [comment]
`pip install pymc-learn==0.0.1rc2` or `pip install -U pymc-learn` fixes this.
